apiVersion: v1
kind: Service
metadata:
  name: casting-be-service
spec:
  selector:
    app: castingzonesbe
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30011