apiVersion: v1
kind: Service
metadata:
  name: casting-service
spec:
  selector:
    app: castingzonesui
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30009